### ISSUE TITLE
running "docker-compose up" produces error

### ISSUE THREAD

**Issue by laisee** [tokenbrowser/token-app-js#5]
postgres_1         | LOG:  invalid record length at 0/151A8E8: wanted 24, got 0
postgres_1         | LOG:  redo done at 0/151A8C0
postgres_1         | LOG:  last completed transaction was at log time 2017-04-21 00:35:34.139695+00
postgres_1         | LOG:  MultiXact member wraparound protections are now enabled
postgres_1         | LOG:  database system is ready to accept connections
postgres_1         | LOG:  autovacuum launcher started
bot_1              | [nodemon] 1.11.0
bot_1              | [nodemon] to restart at any time, enter `rs`
bot_1              | [nodemon] watching: *.*
bot_1              | [nodemon] starting `node src/bot.js config.yml`
bot_1              | Fiat: Fetching rates
bot_1              | Address: 0xa92192541c47edaa8c7c07228594c7212b9d8161
headless-client_1  | com.bakkenbaeck.token.headless.TokenHeadlessClientConfiguration@7b1d7fff
bot_1              | Fiat: Rates initialized successfully
headless-client_1  | [main] INFO org.flywaydb.core.internal.util.VersionPrinter - Flyway 4.1.0 by Boxfuse
headless-client_1  | [main] INFO org.flywaydb.core.internal.dbsupport.DbSupportFactory - Database: jdbc:postgresql://postgres:5432/token (PostgreSQL 9.6)
headless-client_1  | [main] INFO org.flywaydb.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.109s)
headless-client_1  | [main] INFO org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1
headless-client_1  | [main] INFO org.flywaydb.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
headless-client_1  | Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: Empty key
headless-client_1  | 	at org.bitcoinj.crypto.PBKDF2SHA512.derive(PBKDF2SHA512.java:61)
headless-client_1  | 	at org.bitcoinj.crypto.MnemonicCode.toSeed(MnemonicCode.java:134)
headless-client_1  | 	at org.bitcoinj.wallet.DeterministicSeed.<init>(DeterministicSeed.java:81)
headless-client_1  | 	at org.bitcoinj.wallet.DeterministicSeed.<init>(DeterministicSeed.java:54)
headless-client_1  | 	at com.bakkenbaeck.token.crypto.HDWallet.initFromMasterSeed(HDWallet.java:88)
headless-client_1  | 	at com.bakkenbaeck.token.crypto.HDWallet.initWallet(HDWallet.java:65)
headless-client_1  | 	at com.bakkenbaeck.token.crypto.HDWallet.init(HDWallet.java:43)
headless-client_1  | 	at com.bakkenbaeck.token.headless.TokenHeadlessClient.main(TokenHeadlessClient.java:80)
headless-client_1  | Caused by: java.lang.IllegalArgumentException: Empty key
headless-client_1  | 	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
headless-client_1  | 	at org.bitcoinj.crypto.PBKDF2SHA512.F(PBKDF2SHA512.java:74)
headless-client_1  | 	at org.bitcoinj.crypto.PBKDF2SHA512.derive(PBKDF2SHA512.java:56)

**Comment by faymontage** [comment]
I'll put in a sanity check for this case to give a better log line and die early - but the issue is that the `TOKEN_APP_SEED` env var does not contain a value. Does adding one to your docker-compose.yml config file solve the issue?

**Comment by laisee** [comment]
Yes, that resolves the issue. Adding some more detail to logging output
would help
