### ISSUE TITLE
headless-client_1  | Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: Empty key

### ISSUE THREAD

**Issue by rbaskam** [tokenbrowser/token-app-js#8]
Hi,

I've been trying to get the token app running on my local machine using Docker (Using toolbox if that's a problem) On windows 10. Ran docker-compose up and then this error appears. I can't seem to find any fixes online. Hoping you might have an idea for a fix. Thank you in advance

`            | [nodemon] starting `node src/bot.js config.yml`
bot_1              | Fiat: Fetching rates
bot_1              | Address:
headless-client_1  | com.bakkenbaeck.token.headless.TokenHeadlessClientConfiguration@7b1d7fff
headless-client_1  | [main] INFO org.flywaydb.core.internal.util.VersionPrinter - Flyway 4.1.0 by Boxfuse
headless-client_1  | [main] INFO org.flywaydb.core.internal.dbsupport.DbSupportFactory - Database: jdbc:postgresql://postgres:5432/token (PostgreSQL 9.6)
headless-client_1  | [main] INFO org.flywaydb.core.internal.command.DbValidate - Successfully validated 1 migration (execution time 00:00.091s)
headless-client_1  | [main] INFO org.flywaydb.core.internal.command.DbMigrate - Current version of schema "public": 1
headless-client_1  | [main] INFO org.flywaydb.core.internal.command.DbMigrate - Schema "public" is up to date. No migration necessary.
headless-client_1  | Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: Empty key
headless-client_1  |    at org.bitcoinj.crypto.PBKDF2SHA512.derive(PBKDF2SHA512.java:61)
headless-client_1  |    at org.bitcoinj.crypto.MnemonicCode.toSeed(MnemonicCode.java:134)
headless-client_1  |    at org.bitcoinj.wallet.DeterministicSeed.<init>(DeterministicSeed.java:81)
headless-client_1  |    at org.bitcoinj.wallet.DeterministicSeed.<init>(DeterministicSeed.java:54)
headless-client_1  |    at com.bakkenbaeck.token.crypto.HDWallet.initFromMasterSeed(HDWallet.java:88)
headless-client_1  |    at com.bakkenbaeck.token.crypto.HDWallet.initWallet(HDWallet.java:65)
headless-client_1  |    at com.bakkenbaeck.token.crypto.HDWallet.init(HDWallet.java:43)
headless-client_1  |    at com.bakkenbaeck.token.headless.TokenHeadlessClient.main(TokenHeadlessClient.java:80)
headless-client_1  | Caused by: java.lang.IllegalArgumentException: Empty key
headless-client_1  |    at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:96)
headless-client_1  |    at org.bitcoinj.crypto.PBKDF2SHA512.F(PBKDF2SHA512.java:74)
headless-client_1  |    at org.bitcoinj.crypto.PBKDF2SHA512.derive(PBKDF2SHA512.java:56)
headless-client_1  |    ... 7 more`

**Comment by faymontage** [comment]
This is likely because `TOKEN_APP_SEED` env var does not contain a value - make sure your docker-compose.yml config contains all the required fields: http://developers.tokenbrowser.com/docs/configuration

**Comment by rbaskam** [comment]
Doh!!! Didn't hit save!! Thank you and sorry for wasting your time!
